name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run Flutter doctor
      - name: Flutter doctor
        run: flutter doctor

      # Run tests
      - name: Run tests
        run: flutter test

      # Build APK (release mode)
      - name: Build app (APK)
        run: flutter build apk --release

      # List APK files (debugging step)
      - name: List APKs
        run: ls -alh build/app/outputs/flutter-apk/

      # (Optional) Test server connection
      - name: Test server connection
        run: curl -I https://your-real-server.com  # Replace with your actual server URL

      # Deploy to server (optional)
      - name: Deploy to server
        if: success()
        env:
          DEPLOY_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "Deploying APK to server..."
          curl -X POST -H "Authorization: Bearer $TOKEN" \
               -F "file=@build/app/outputs/flutter-apk/app-release.apk" \
               https://your-real-server.com/api/upload  # Replace with actual endpoint
