name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run Flutter doctor (optional for diagnosing environment)
      - name: Flutter doctor
        run: flutter doctor

      # Run tests
      - name: Run tests
        run: flutter test

      # Build APK (release mode)
      - name: Build app (APK)
        run: flutter build apk --release

      # List APK files (debugging step to ensure APK was built)
      - name: List APKs
        run: ls -alh build/app/outputs/flutter-apk/

      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # GitHub automatically provides this secret
        with:
          tag_name: v1.0.0  # Adjust the version tag as necessary
          release_name: Release v1.0.0  # Adjust the release name as necessary
          draft: false
          prerelease: false

      # Upload APK to GitHub Release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # GitHub automatically provides this secret
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
